[packages]

[packages.execucao2022]

"path" = "https://raw.githubusercontent.com/splor-mg/dados-armazem-siafi-2022/main/datapackage.json"
"token" = "GIT_HUB_TOKEN"
"resources" = ["receita"]

[packages.execucao2023]

"path" = "https://raw.githubusercontent.com/splor-mg/dados-armazem-siafi-2023/main/datapackage.json"
"token" = "GIT_HUB_TOKEN"
"resources" = ["receita"]

[packages.execucao2024]

"path" = "https://raw.githubusercontent.com/splor-mg/dados-armazem-siafi-2024/main/datapackage.json"
"token" = "GIT_HUB_TOKEN"
"resources" = ["receita"]

[packages.execucao2025]

"path" = "https://raw.githubusercontent.com/splor-mg/dados-armazem-siafi-2025/main/datapackage.json"
"token" = "GIT_HUB_TOKEN"
"resources" = ["receita"]


[packages.sisor2026]

"path" = "https://raw.githubusercontent.com/splor-mg/dados-sisor-2026/main/datapackage.json"
"token" = "GIT_HUB_TOKEN"
"resources" = ["base_orcam_receita_fiscal"]

