[packages]


[packages.siafi_2024]

# repositório dados-armazem-siafi 2 anos anteriores à atualização do painel
"path" = "https://raw.githubusercontent.com/splor-mg/dados-armazem-siafi-2024/main/datapackage.json"
"token" = "GH_TOKEN"
"resources" = ["receita"]

[packages.siafi_2025]

# repositório dados-armazem-siafi 1 ano anterior à atualização do painel
"path" = "https://raw.githubusercontent.com/splor-mg/dados-armazem-siafi-2025/main/datapackage.json"
"token" = "GH_TOKEN"
"resources" = ["receita"]

[packages.siafi_2026]

# repositório dados-armazem-siafi no ano da atualização do painel
"path" = "https://raw.githubusercontent.com/splor-mg/dados-armazem-siafi-2026/main/datapackage.json"
"token" = "GH_TOKEN"
"resources" = ["receita"]


[packages.reestimativa_2026]

# repositório dados-reestimativa-2026 no ano da atualização do painel
"path" = "https://raw.githubusercontent.com/splor-mg/dados-reestimativa-2026/main/datapackage.json"
"token" = "GH_TOKEN"
"resources" = ["reest_rec"]


